src/Entity/Station.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StationRepository")
 */
class Station
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $numer_sta;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    public function __construct()
    {
        $this->weatherData = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getNumerSta(): ?int
    {
        return $this->numer_sta;
    }

    public function setNumerSta(int $numer_sta): self
    {
        $this->numer_sta = $numer_sta;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|WeatherData[]
     */
    public function getWeatherData(): Collection
    {
        return $this->weatherData;
    }

    public function addWeatherData(WeatherData $weatherData): self
    {
        if (!$this->weatherData->contains($weatherData)) {
            $this->weatherData[] = $weatherData;
            $weatherData->setNumerSta($this);
        }

        return $this;
    }

    public function removeWeatherData(WeatherData $weatherData): self
    {
        if ($this->weatherData->contains($weatherData)) {
            $this->weatherData->removeElement($weatherData);
            // set the owning side to null (unless already changed)
            if ($weatherData->getNumerSta() === $this) {
                $weatherData->setNumerSta(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\Entity\WeatherData;
use App\Repository\WeatherDataRepository;

class MainController extends Controller
{

    private $stations = array(
        "7005" => "ABBEVILLE",
        "7015" => "LILLE-LESQUIN",
        "7020" => "PTE DE LA HAGUE",
        "7027" => "CAEN-CARPIQUET",
        "7037" => "ROUEN-BOOS",
        "7072" => "REIMS-PRUNAY",
        "7110" => "BREST-GUIPAVAS",
        "7117" => "PLOUMANAC'H",
        "7130" => "RENNES-ST JACQUES",
        "7139" => "ALENCON",
        "7149" => "ORLY",
        "7168" => "TROYES-BARBEREY",
        "7181" => "NANCY-OCHEY",
        "7190" => "STRASBOURG-ENTZHEIM",
        "7207" => "BELLE ILE-LE TALUT",
        "7222" => "NANTES-BOUGUENAIS",
        "7240" => "TOURS",
        "7255" => "BOURGES",
        "7280" => "DIJON-LONGVIC",
        "7299" => "BALE-MULHOUSE",
        "7314" => "PTE DE CHASSIRON",
        "7335" => "POITIERS-BIARD",
        "7434" => "LIMOGES-BELLEGARDE",
        "7460" => "CLERMONT-FD",
        "7471" => "LE PUY-LOUDES",
        "7481" => "LYON-ST EXUPERY",
        "7510" => "BORDEAUX-MERIGNAC",
        "7535" => "GOURDON",
        "7558" => "MILLAU",
        "7577" => "MONTELIMAR",
        "7591" => "EMBRUN",
        "7607" => "MONT-DE-MARSAN",
        "7621" => "TARBES-OSSUN",
        "7627" => "ST GIRONS",
        "7630" => "TOULOUSE-BLAGNAC",
        "7643" => "MONTPELLIER",
        "7650" => "MARIGNANE",
        "7661" => "CAP CEPET",
        "7690" => "NICE",
        "7747" => "PERPIGNAN",
        "7761" => "AJACCIO",
        "7790" => "BASTIA",
        "61968" => "GLORIEUSES",
        "61970" => "JUAN DE NOVA",
        "61972" => "EUROPA",
        "61976" => "TROMELIN",
        "61980" => "GILLOT-AEROPORT",
        "61996" => "NOUVELLE AMSTERDAM",
        "61997" => "CROZET",
        "61998" => "KERGUELEN",
        "67005" => "PAMANDZI",
        "71805" => "ST-PIERRE",
        "78890" => "LA DESIRADE METEO",
        "78894" => "ST-BARTHELEMY METEO",
        "78897" => "LE RAIZET AERO",
        "78922" => "TRINITE-CARAVEL",
        "78925" => "LAMENTIN-AERO",
        "81401" => "SAINT LAURENT",
        "81405" => "CAYENNE-MATOURY",
        "81408" => "SAINT GEORGES",
        "81415" => "MARIPASOULA",
        "89642" => "DUMONT D'URVILLE"
    );

    /**
     * @Route("/meteo/ordered/{station_id}", name="FINALU")
     */
    public function corruption($station_id = 7005)
    {
        $max_temp = 273.15;
        $min_temp;
        $ave_wind;

        $datas = $this->getDoctrine()
        ->getRepository(WeatherData::class)
        ->groupByStation($station_id);

        foreach($datas as &$data){
            $data['ww'] = $this->imageTemps($data['ww']);
            $min_temp = $data['t'];
            $max_temp = max($max_temp, $data['t']);
            $min_temp = min($min_temp, $data['t']);
            $ave_wind[] = $data['ff'];
        }
        $ave_wind = array_sum($ave_wind) / count($ave_wind);

        return $this->render('main/finalu.html.twig', [
            'stations' => $this->stations,
            'datas' => $datas,
            'max'=> $max_temp,
            'min'=> $min_temp,
            'ave'=> $ave_wind
        ]);
    }

    public function imageTemps(?int $temps){
        switch (true) {
            case in_array($temps, range(0,19)):
                return 'picto/sunny.png';
            case in_array($temps, range(20,29)):
                return 'picto/clouds-and-sun.png';
            case in_array($temps, range(30,39)):
                return 'picto/weather-1.png';
            case in_array($temps, range(40,49)):
                return 'picto/morning-snow.png';
            case in_array($temps, range(50,59)):
                return 'picto/tide-1.png';
            case in_array($temps, range(60,69)):
                return 'picto/raining.png';
            case in_array($temps, range(70,79)):
                return 'picto/raining.png';
            case in_array($temps, range(80,94)):
                return 'picto/summer-rain.png';
            case in_array($temps, range(95,99)):
                return 'picto/storm-2.png';
        }
    }

    /**
     * @Route("/meteo/stations", name="main")
     */
    public function index()
    {
        $datas = $this->getDoctrine()
        ->getRepository(WeatherData::class)
        ->orderByAlphabetical();

        return $this->render('main/index.html.twig', [
            'stations' => $this->stations,
            'datas' => $datas
        ]);
    }

    /**
     * @Route("/meteo/menu", name="menu")
     */
    public function menuShow()
    {
        return $this->render('main/menu.html.twig');
    }

    /**
     * @Route("/meteo/stations/rain", name="stationsRain")
     */
    public function byRain()
    {
        $datas = $this->getDoctrine()
        ->getRepository(WeatherData::class)
        ->filterByRain();

        return $this->render('main/filtered.html.twig', [
            'stations' => $this->stations,
            'datas' => $datas
        ]);
    }

    /**
     * @Route("/meteo/stations/{stationId}", name="byId", requirements={"id"="\d+"})
     */
    public function byId($stationId)
    {
        $datas = $this->getDoctrine()
        ->getRepository(WeatherData::class)
        ->findOneBy(['station' => $stationId]);

        if (!$datas) {
            return $this->render('main/error.html.twig',['error'=>'id']);
        }

        return $this->render('main/station.html.twig', [
            'stations' => $this->stations,
            'data' => $datas
        ]);
    }

    /**
     * @Route("/meteo/stations/order/{param}", name="orderByParam")
     */
    public function orderBy($param)
    {
        $datas = null;
        if($param == 'wind_direction') {
            $datas = $this->getDoctrine()
            ->getRepository(WeatherData::class)
            ->filterByWindD();
        }
        else if($param == 'temperature') {
            $datas = $this->getDoctrine()
            ->getRepository(WeatherData::class)
            ->filterByTemp();
        }
        else{
            return $this->render('main/error.html.twig',['error'=>'order']);
        }

        return $this->render('main/filtered.html.twig', [
            'stations' => $this->stations,
            'datas' => $datas
        ]);

    }


}

templates/main/error.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% if error == "id" %}
La station auquel vous essayé d'accéder n'est pas disponible ou n'existe pas, veuillez en écrire une autre.
    {% elseif error == "order" %}
Le filtre sélectionné n'existe pas dsl
    {% endif %}
{% endblock %}

templates/main/filtered.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div>
    {% for data in datas %}
        <div>
            <div> {{ stations[data.numerSta] }} </div><br>
            <div>Pour la date {{ data.date | date("m/d/Y") }}
            <ul>
                <li> Température: {{ data.t }} K</li>
                <li> Direction du vent: {{ data.dd }} °</li>
                <li> Vitesse du vent: {{ data.ff }} m/s</li>
                <li> Humidité dans l'air: {{ data.u}} %</li>
                <li> temps : {{ data.ww }}</li>
            </ul>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/main/finalu.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<h1 class="station">{{ stations[datas[0].numer_sta] }}</h1>
<div class="container">
    <div class="data_left">
        <h1>Samedi</h1>
    {% for data in datas %}
        {% if data.date |slice(6, 2) == 12 %}
        <div class="data" data-id="{{ data.date |slice(8, 2) }}">
            <div class="tabs">
                <div class="tab" data-id="00">00h</div>
                <div class="tab" data-id="03">03h</div>
                <div class="tab" data-id="06">06h</div>
                <div class="tab" data-id="09">09h</div>
                <div class="tab" data-id="12">12h</div>
                <div class="tab" data-id="15">15h</div>
                <div class="tab" data-id="18">18h</div>
                <div class="tab" data-id="21">21h</div>
            </div>
        <div class="data_container">
            <h2 class="date">
                {{ data.date |slice(6, 2) }}/{{ data.date |slice(4, 2) }}/{{ data.date |slice(0, 4) }}<br>
                {{ data.date |slice(8, 2) }}h
            </h2>
            <div><img class="temps" src="{{ asset(data.ww) }}"><br></div>
            <ul class="données">
                 Température: {{ data.t - 273.15 }} °C<br>
                 Direction du vent: {{ data.dd }} °<br>
                 Vitesse du vent: {{ data.ff }} m/s<br>
                 Humidité dans l'air: {{ data.u}} %<br>
            </ul>
        </div>
        </div>
        {% endif %}
    {% endfor %}
    </div>
    <div class="middle_informations">
            <h2>Récapitulatif:</h2>
            Température max :
        <h3>{{ max - 273.15}}°C</h3><br>
            Température min :
        <h3>{{ min - 273.15 }}°C</h3>
            Vitesse moyenne du vent :
        <h3>{{ ave }}m/s</h3>
    </div>
    <div class="data_right">
        <h1>Dimanche</h1>
    {% for data in datas %}
        {% if data.date |slice(6, 2) == 13 %}
        <div class="data" data-id="{{ data.date |slice(8, 2) }}">
            <div class="tabs">
                <div class="tab" data-id="00">00h</div>
                <div class="tab" data-id="03">03h</div>
                <div class="tab" data-id="06">06h</div>
                <div class="tab" data-id="09">09h</div>
                <div class="tab" data-id="12">12h</div>
                <div class="tab" data-id="15">15h</div>
                <div class="tab" data-id="18">18h</div>
            </div>
        <div class="data_container">
            <h2 class="date">
                {{ data.date |slice(6, 2) }}/{{ data.date |slice(4, 2) }}/{{ data.date |slice(0, 4) }}<br>
                {{ data.date |slice(8, 2) }}h
            </h2>
            <div><img class="temps" src="{{ asset(data.ww) }}"><br></div>
            <ul class="données">
                 Température: {{ data.t - 273.15 }} °C<br>
                 Direction du vent: {{ data.dd }} °<br>
                 Vitesse du vent: {{ data.ff }} m/s<br>
                 Humidité dans l'air: {{ data.u}} %<br>
            </ul>
        </div>
        </div>
        {% endif %}
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div>
    {% for data in datas %}
        <div>
            <div> {{ stations[data.numer_sta] }} </div><br>
            <div>Pour la date {{ data.date }}
            <ul>
                <li> Température: {{ data.t }} K</li>
                <li> Direction du vent: {{ data.dd }} °</li>
                <li> Vitesse du vent: {{ data.ff }} m/s</li>
                <li> Humidité dans l'air: {{ data.u}} %</li>
                <li> temps : {{ data.ww }}</li>
            </ul>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/main/menu.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div>
<a href="{{ path("main") }}">Toutes les stations</a><br>
<a href="{{ path("stationsRain") }}">La pluie</a><br>
<a href="/meteo/stations/order/wind_direction">La direction vent</a><br>
<a href="/meteo/stations/order/temperature">La temperature</a><br>
/meteo/stations/{stationId} Pour accéder à une station<br>

</div>
{% endblock %}

templates/main/station.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div>
        <div>
            <div> {{ stations[data.numerSta] }} </div><br>
            <div>Pour la date {{ data.date | date("m/d/Y") }}
            <ul>
                <li> Température: {{ data.t }} K</li>
                <li> Direction du vent: {{ data.dd }} °</li>
                <li> Vitesse du vent: {{ data.ff }} m/s</li>
                <li> Humidité dans l'air: {{ data.u}} %</li>
                <li> temps : {{ data.ww }}</li>
            </ul>
        </div>
</div>
{% endblock %}